### ISSUE TITLE
Decentralized / Distributed Vuvuzela

### ISSUE THREAD

**Issue by davidlazar** [vuvuzela/vuvuzela#10]
Ideally, anyone could contribute a small Vuvuzela server, similar to how Tor works.

**Comment by taoeffect** [comment]
Would it be possible to use a DHT and/or an ethereum smart contract as the "server" and make Vuvuzela more p2p instead of client/server based?

**Comment by DevelopingUnicorn** [comment]
Which Ports are used by the Server? For Portforwarding this would be very useful to know!

**Comment by farazfazli** [comment]
@DevelopingUnicorn The default port is 2718. See https://github.com/davidlazar/vuvuzela/blob/cf61af556e43292b2c0283aa46334ffa0b9ba31c/params.go

**Comment by davidlazar** [comment]
This is being tackled by the Stadium project. An early preprint is available here: https://eprint.iacr.org/2016/943

**Comment by eggyal** [comment]
Is it anticipated that Stadium and Vuvuzela might be combined in the future?  How will the projects interplay?

**Comment by davidlazar** [comment]
Our new Karaoke paper also addresses this: https://davidlazar.org/papers/karaoke.pdf

The plan for the time being is to continue deploying Vuvuzela's topology until scaling becomes an issue.
