### ISSUE TITLE
panic: invalid argument

### ISSUE THREAD

**Issue by Akito13** [vuvuzela/vuvuzela#29]
I just reserved a username on the homepage and after a couple of tries I managed to successfully install `vuvuzela-client` on Ubuntu Xenial with ` go version go1.9.2 linux/amd64`. Unfortunately, every time I try to register my username, the login fails:
```

user@hostname:~$ vuvuzela-client -username user
panic: invalid argument

goroutine 1 [running]:
main.(*GuiClient).Run(0xc42023a400, 0xc420230000)
        /home/user/go/src/vuvuzela.io/vuvuzela/cmd/vuvuzela-client/gui.go:1076 +0x7b7
main.main()
        /home/user/go/src/vuvuzela.io/vuvuzela/cmd/vuvuzela-client/main.go:54 +0x394
```
**UPDATE1**
I did the same procedure of installing the client on a Debian Stretch 64-bit VM and it works immediately. What is the issue on Ubuntu? The go version on the Debian VM: `go version go1.8.1 linux/amd64`

**Comment by davidlazar** [comment]
How did you build the client on Ubuntu?

**Comment by Akito13** [comment]
@DavidLazar `$ go get -u vuvuzela.io/vuvuzela/cmd/vuvuzela-client`

**Comment by davidlazar** [comment]
Could you try to build the client with an empty GOPATH (e.g., `export GOPATH=/tmp/go`)

**Comment by Akito13** [comment]
user@hostname:~$ export GOPATH=/tmp/go
user@hostname:~$ export PATH=$GOPATH/bin:$PATH
user@hostname:~$ go get -u vuvuzela.io/vuvuzela/cmd/vuvuzela-client
user@hostname:~$ vuvuzela-client -username user
panic: invalid argument

goroutine 1 [running]:
main.(*GuiClient).Run(0xc4201d8480, 0xc4201d0000)
        /tmp/go/src/vuvuzela.io/vuvuzela/cmd/vuvuzela-client/gui.go:1076 +0x7b7
main.main()
        /tmp/go/src/vuvuzela.io/vuvuzela/cmd/vuvuzela-client/main.go:54 +0x394
user@hostname:~$

**Comment by oltdaniel** [comment]
I think the error is thrown by https://github.com/vuvuzela/vuvuzela/blob/master/cmd/vuvuzela-client/gui.go#L508 and so on by the `gocui` library.

**Comment by davidlazar** [comment]
Is this still an issue?

**Comment by Akito13** [comment]
> Is this still an issue?

No, but you should check out the [alpenhorn issues](https://github.com/vuvuzela/alpenhorn/issues).
