### ISSUE TITLE
cant install vuvuzela

### ISSUE THREAD

**Issue by agrinevich** [vuvuzela/vuvuzela#32]
Xubuntru 17.10: 
go get -u vuvuzela.io/vuvuzela/cmd/vuvuzela-client 
gives me 
"# vuvuzela.io/crypto/bn256
exec: "gcc": executable file not found in $PATH"

Windows-10:
go get -u vuvuzela.io/vuvuzela/cmd/vuvuzela-client 
gives me 
"# vuvuzela.io/crypto/bn256
exec: "gcc": executable file not found in $PATH"

Debian 9:
"# vuvuzela.io/crypto/bn256
exec: "gcc": executable file not found in $PATH"

**Comment by dojiao** [comment]
try <code>sudo apt install gcc</code> on Ubuntu

This happens when you don't have a gcc compiler or didn't set PATH for gcc

On Windows, installing gcc compiler is a bit more complex than Ubuntu.

You can Google **install gcc in Windows** to fix this problem on Windows

**Comment by agrinevich** [comment]
I have installed gcc on Debian9 and there's no visible errors but when I try to run vuvuzela-client I got error: 

> bash: vuvuzela-client: command not found

It would be nice to mention prerequisites on "Getting Started" page.

**Comment by agrinevich** [comment]
I can run vuvuzela from ~/go/bin/ on Debian, so it's just my mistake. I like vuvuzela very much. I'm sorry, guys.

**Comment by oltdaniel** [comment]
Shouls be closed if there aren't any reaming issues.

**Comment by aviwad** [comment]
Can this be opened? Following the instructions, go never installs the vuvuzela client. If I run the instructions given by @dojiao, running go run main.go says
```
# command-line-arguments
./main.go:50:9: undefined: GuiClient
./main.go:61:9: undefined: launchStatus

```

**Comment by davidlazar** [comment]
What happens when you run `go get -u vuvuzela.io/vuvuzela/cmd/vuvuzela-client` ?
