### ISSUE TITLE
connection error since May 16

### ISSUE THREAD

**Issue by agrinevich** [vuvuzela/vuvuzela#36]
i have updated app "go get -u vuvuzela.io/vuvuzela/cmd/vuvuzela-client" but it does not help

 -!- Connection error: inconsistent PKG status for "randy":
  ·  PKG pkg1.vuvuzela.io:8443: OK
  ·  PKG nickolai.srv.vuvuzela.io:54331: Post https://nickolai.srv.vuvuzela.io:
 54331/status: dial tcp 50.202.194.198:54331: connect: connection refused
  ·  PKG pkg2.vuvuzela.io:8443: OK
 -!- Type /connect after resolving the issue to try again.

**Comment by zeldovich** [comment]
Yeah, sorry about that, we've been trying to test some updates to these PKG servers, but got stuck halfway through.  I downgraded my PKG, so hopefully it should be working again.

**Comment by agrinevich** [comment]
It works now! Thank you for your work, I think Vuvuzela is very interesting project.
