### ISSUE TITLE
[Question] The reason for operating in rounds

### ISSUE THREAD

**Issue by divya84** [vuvuzela/vuvuzela#38]
Hi, this is not an issue but a question about the approach. In trying to read and understand the Vuvuzela research paper, I couldn't find the reason for why it operates in rounds. Is this a requirement for differential privacy? If there is prior work that helps explain this, could you point me towards that. Thanks.

**Comment by davidlazar** [comment]
Sending messages in rounds avoids metadata about when users communicate. Each round, every user sends and receives a message from the system, regardless of whether they are in an active conversation. 

Rounds also simplify the differential privacy analysis. We can reason about the leakage of one round and then extend this reasoning to many rounds using the composition theorem.
