### ISSUE TITLE
inconsistent PKG status

### ISSUE THREAD

**Issue by aa153** [vuvuzela/vuvuzela#40]
I've successfully created account via vuvuzela.io.
Updated vuvuzela client.
But after start got error message (screenshot
![screenshot_2018-07-20_21-38-44](https://user-images.githubusercontent.com/16975604/43019417-8eb489ac-8c65-11e8-9884-75c49f2e3c83.png)
).

**Comment by davidlazar** [comment]
Thanks for your interest in Vuvuzela. User registration will be ready when issue #35 is closed.
