### ISSUE TITLE
How to use usernames instead of e-mail addresses

### ISSUE THREAD

**Issue by Akito13** [vuvuzela/vuvuzela#41]
So these past months I didn't have the possibility to pursue my interest in vuvuzela due to reasons. Now I want to return to vuvuzela and notice that it registers usernames as actual e-mail addresses. At first, I thought that this is optional for those who can't keep a tidy environment for their data, but I don't see any possibility now to use the original usernames. This is very unfortunate for people like me, because I can keep my data environment tidy and I don't see any purpose in using an actual e-mail address to register my token. In fact, it is a huge counter argument for me to keep using this program if I actually **have to** register using a valid e-mail address. The whole anonymity point gets kind of wonky, as well. Especially considering, that vuvuzela is revolutionary in regards to protecting metadata while e-mails are as clear as a drinking glass. Even with protected e-mail services, the metadata is easily discoverable.
It gets even more weird, since one such untidy person can still lose access to their e-mail, so the whole recovery point becomes futile.

Did I misunderstand something and I can use my original username or do I really have to register using a valid e-mail address now?

```
 -!- Connection error: inconsistent PKG status for "user":
  ·  PKG pkg1.vuvuzela.io:8443: invalid username: username must be a valid email address: user
  ·  PKG nickolai.srv.vuvuzela.io:54331: invalid username: username must be a valid email address: user
  ·  PKG pkg2.vuvuzela.io:8443: invalid username: username must be a valid email address: user
 -!- Type /connect after resolving the issue to try again.
```

**Comment by davidlazar** [comment]
As Nickolai explains in issue #30,

> The metadata that Vuvuzela tries to protect is "which users are communicating", rather than "which users are connected to Vuvuzela" or "what is this user's Vuvuzela username".

We switched to using email addresses instead of usernames since it allows us to implement a plan to reset accounts when users lose their keys (see issue #35). We probably wont be going back to regular usernames and the original usernames are no longer usable.
