### ISSUE TITLE
[Documentation] Vuvuzela vs Ricochet

### ISSUE THREAD

**Issue by gjhklfdsa** [vuvuzela/vuvuzela#45]
Is there any in depth analysis of the pros/cons of using Vuvuzela over [Ricochet](https://ricochet.im/)?

**Comment by davidlazar** [comment]
Ricochet is vulnerable to traffic analysis attacks. Our [SOSP 2015 paper](https://vuvuzela.io/static/vuvuzela.pdf) goes into more detail.
